### ISSUE TITLE
getDocument doesnt deserialize the same way as query() when using VelocyJack

### ISSUE THREAD

**Issue by fdominik** [arangodb/arangodb-java-driver#271] opened 2019-06-20 12:28 UTC
I am trying to use Arango Java  Driver (v.5.0.3). I am configuring ArangoDB in this way:
 ```
arango = new ArangoDB.Builder()
                .serializer(velocyJack)
                .password(password)
                .host(host, port)
                .maxConnections(maxConnections)
                .user(userId).build();
```
Where velocyJack is the `VelocyJack velocyJack = new VelocyJack();` with configured serializers.
It works fine when I do arango.query(), where I send my POJO to be returned. It scans for the Jackson Annotations and behaves according them.
also when I do collection.insertDocument(), the serializer woks fine.
Where I do struggle is when doing arango.getDocument(), where I also send the Class name.
When I retrieve a document using AQL specification and query(), it is transfered as per Jackson. However when I get the same document using getDocument(), it doesn't reflect the Jackson annotations. It just omits them like they wouldn't exists. So it looks that maybe for getDocument there is registered other serializer then for query()?

Here is the velocyJack configuration:
 ```
velocyJack.configure((mapper) -> {
                       mapper = new VPackMapper();
            mapper.configure(SerializationFeature.FAIL_ON_EMPTY_BEANS, false);
            mapper.configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);
            mapper.setVisibility(PropertyAccessor.FIELD, Visibility.ANY);
            SimpleModule module = new SimpleModule();
            module.addSerializer(VPackSlice.class, VPackSerializers.VPACK);
            module.addSerializer(Date.class, VPackSerializers.UTIL_DATE);
            module.addSerializer(java.sql.Date.class, VPackSerializers.SQL_DATE);
            module.addSerializer(Timestamp.class, VPackSerializers.SQL_TIMESTAMP);
            module.addSerializer(BaseDocument.class, VPackSerializers.BASE_DOCUMENT);
            module.addSerializer(BaseEdgeDocument.class, VPackSerializers.BASE_EDGE_DOCUMENT);
            module.addDeserializer(VPackSlice.class, VPackDeserializers.VPACK);
            module.addDeserializer(Date.class, VPackDeserializers.UTIL_DATE);
            module.addDeserializer(java.sql.Date.class, VPackDeserializers.SQL_DATE);
            module.addDeserializer(Timestamp.class, VPackDeserializers.SQL_TIMESTAMP);
            module.addDeserializer(BaseDocument.class, VPackDeserializers.BASE_DOCUMENT);
            module.addDeserializer(BaseEdgeDocument.class, VPackDeserializers.BASE_EDGE_DOCUMENT);

            mapper.registerModule(module);
        });
```

**Comment by rashtao** [comment] 2019-08-07 10:29
related slack thread: https://arangodb-community.slack.com/archives/C1R9YA869/p1561033350006100

**Comment by rashtao** [comment] 2019-08-09 09:49
It could be caused by the usage of the INTERNAL (de)Serializer instead of the CUSTOM one.
As eg: https://github.com/arangodb/arangodb-java-driver/blob/5e7add2c19150830c8ed0bcc17e647372e780286/src/main/java/com/arangodb/internal/ArangoExecutor.java#L47

**Comment by rashtao** [comment] 2019-08-30 12:40
fixed in https://github.com/arangodb/arangodb-java-driver/releases/tag/v6.1.0

**Closed by rashtao** 2019-08-30 12:40 UTC
