### ISSUE TITLE
Support to Apache TinkerPop API

### ISSUE THREAD

**Issue by otaviojava** [arangodb/arangodb-java-driver#154] opened 2017-10-02 13:04 UTC
Hey,

Is there any plans to ArangoDB has support to Apache TinkerPop in the graph database?
http://tinkerpop.apache.org/

**Comment by jean-amana** [comment] 2017-10-16 11:12
It would indeed be very useful.
This is a criteria for the adoption of ArangoDB in my company.

**Comment by dothebart** [comment] 2017-10-17 08:23
closing as duplicate of https://github.com/arangodb/blueprints-arangodb-graph/issues/15

**Closed by dothebart** 2017-10-17 08:23 UTC
