### ISSUE TITLE
HTTP protocol auth failed

### ISSUE THREAD

**Issue by wenerme** [arangodb/arangodb-java-driver#140] opened 2017-08-04 17:28 UTC
Driver use basic auth , but server need jwt, always return 401

```
00:59:39.922 [main] DEBUG org.apache.http.headers - http-outgoing-0 << HTTP/1.1 401 Unauthorized
00:59:39.922 [main] DEBUG org.apache.http.headers - http-outgoing-0 << Server: nginx
00:59:39.922 [main] DEBUG org.apache.http.headers - http-outgoing-0 << Date: Fri, 04 Aug 2017 16:59:41 GMT
00:59:39.922 [main] DEBUG org.apache.http.headers - http-outgoing-0 << Content-Type: text/plain; charset=utf-8
00:59:39.922 [main] DEBUG org.apache.http.headers - http-outgoing-0 << Content-Length: 0
00:59:39.922 [main] DEBUG org.apache.http.headers - http-outgoing-0 << Connection: keep-alive
00:59:39.922 [main] DEBUG org.apache.http.headers - http-outgoing-0 << X-Content-Type-Options: nosniff
00:59:39.922 [main] DEBUG org.apache.http.headers - http-outgoing-0 << Www-Authenticate: Bearer token_type="JWT", realm="ArangoDB"
```

```java
        ArangoDB db = new Builder()
            .useSsl(true)
            .useProtocol(Protocol.HTTP_JSON)
            .host("HOST", 443)
            .user("USER")
            .password("PASS")
            .build();
        System.out.println(db.getAccessibleDatabases());
```

The server use nginx as reverse proxy

**Comment by mpv1989** [comment] 2017-08-09 10:43
@wenerme jwt authentication is currently not supported by the driver. I'll discuss this internally whether we have time for it in the near future.

**Comment by rashtao** [comment] 2020-09-08 13:30
duplicate of https://github.com/arangodb/arangodb-java-driver/issues/335

**Closed by rashtao** 2020-09-08 13:30 UTC
Labels: enhancement
