### ISSUE TITLE
com.arangodb.ArangoDBException: Response: 412, Error: 1200 - precondition failed

### ISSUE THREAD

**Issue by oschina** [arangodb/arangodb-java-driver#165] opened 2017-12-14 07:21 UTC
Under what circumstances will this anomaly happen?

And this is a sporadic problem

This exception occur when invoke updateDocument method.

**Comment by mpv1989** [comment] 2018-04-18 09:49
This should only occur when your document, which you try to update, does not exists.

Since this issue is very old I will close it. Feel free to open it again if this problem is still not solved

**Closed by mpv1989** 2018-04-18 09:49 UTC

**Comment by pengyunshan** [comment] 2018-12-11 07:21
So what's the difference between 404 and 412? 404 error also means the request resources not exists.

**Comment by brunoaduarte** [comment] 2020-09-15 19:53
This error still persists on latest version.

**Comment by rashtao** [comment] 2020-09-16 07:50
@brunoaduarte this issue should be fixed in ArangoDB 3.7: https://www.arangodb.com/docs/3.7/release-notes-api-changes37.html#precondition-failed-error-message-changes

In case your problem persists, please open a new issue providing a code snippet to reproduce it.

**Comment by brunoaduarte** [comment] 2020-09-17 14:18
2020-09-17 11:16:41.096 ERROR 26316 --- [-nio-443-exec-7] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.dao.DataAccessResourceFailureException: Response: 412, Error: 1200 - write-write conflict; nested exception is com.arangodb.ArangoDBException: Response: 412, Error: 1200 - write-write conflict] with root cause

com.arangodb.ArangoDBException: Response: 412, Error: 1200 - write-write conflict
