### ISSUE TITLE
Velocystream error during import

### ISSUE THREAD

**Issue by jean-amana** [arangodb/arangodb-java-driver#157] opened 2017-10-17 14:21 UTC
Hi,

Using document import (or insert) with the Java client version 4.2.4 lead to the following kind of error with moderately big amount of data (several million documents) :

`2017-10-17 11:57:41 [pool-4-thread-1] ERROR com.arangodb.internal.velocystream.internal.MessageStore - Reached the end of the stream.
java.io.IOException: Reached the end of the stream.
	at com.arangodb.internal.velocystream.internal.Connection.readBytesIntoBuffer(Connection.java:268)
	at com.arangodb.internal.velocystream.internal.Connection.readBytes(Connection.java:260)
	at com.arangodb.internal.velocystream.internal.Connection.readChunk(Connection.java:237)
	at com.arangodb.internal.velocystream.internal.Connection$1.call(Connection.java:148)
	at com.arangodb.internal.velocystream.internal.Connection$1.call(Connection.java:137)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
...

Caused by: java.util.concurrent.ExecutionException: com.arangodb.ArangoDBException: java.io.IOException: Reached the end of the stream.
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.arangodb.internal.velocystream.internal.ConnectionSync.write(ConnectionSync.java:88)
	... 14 more
Caused by: com.arangodb.ArangoDBException: java.io.IOException: Reached the end of the stream.
	at com.arangodb.internal.velocystream.internal.MessageStore.get(MessageStore.java:73)
	at com.arangodb.internal.velocystream.internal.ConnectionSync$1.call(ConnectionSync.java:82)
	at com.arangodb.internal.velocystream.internal.ConnectionSync$1.call(ConnectionSync.java:79)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.arangodb.internal.velocystream.internal.MessageStore.clear(MessageStore.java:96)
	at com.arangodb.internal.velocystream.internal.Connection$1.call(Connection.java:157)
	at com.arangodb.internal.velocystream.internal.Connection$1.call(Connection.java:137)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Reached the end of the stream.
	at com.arangodb.internal.velocystream.internal.Connection.readBytesIntoBuffer(Connection.java:268)
	at com.arangodb.internal.velocystream.internal.Connection.readBytes(Connection.java:260)
	at com.arangodb.internal.velocystream.internal.Connection.readChunk(Connection.java:237)
	at com.arangodb.internal.velocystream.internal.Connection$1.call(Connection.java:148)
	... 5 more`

More details:
- Error occurs randomly during the import, and crash the client
- This is happening on fresh DB install (v3.2.4 on Linux).
- The waitForSync option seems to reduce the frequency, but not suppress it.
- Importing smaller amount of data (using paging) also seems to reduce the frequency of errors, without suppressing it.
- Import is done using:

`collection.importDocuments(documents,options)`

(documents is a list of BaseDocument).

We got this behavior on two different installs of ArangoDB: 1 single machine (v3.2.2 using Docker) and one cluster of 3 nodes (v3.2.4 on Linux).

Is there any good practice I'm missing in terms of import of big amount of data?

Thanks

**Comment by mpv1989** [comment] 2017-10-23 09:15
@jean-amana I would like to reproduce this. Can you tell me how many documents you try to import with one call of `collection.importDocuments(documents,options)` and can you send me one example document? Thanks

**Comment by jean-amana** [comment] 2017-10-23 09:26
Hi Mark, thanks for reaching out!

The amount of documents sent in a single call is currently at 50000 (I made several experiments with values between 10000 and 500000 with same issue).
Our documents are under NDA so I cannot describe them in details, however they all have the same structure: 20 standard fields (String, Integer, etc.).

**Comment by mpv1989** [comment] 2017-10-25 13:31
@jean-amana do you have SSL enabled?

**Comment by jean-amana** [comment] 2017-10-25 13:49
Hi Mark,

No, we don't have SSL enabled.

**Comment by mpv1989** [comment] 2017-10-27 08:52
@jean-amana I wasn't able to reproduce this neither with single server in docker nor in a cluster setup. Are you able to share the server logs with me? I don't think the problem belongs to the client side.

To reproduce your problem I wrote a small load-test which you can find [here](https://github.com/arangodb-helper/load-test). Maybe you could do a quick test with that in your environment?

I used it with the following options
```
java -jar .\target\arangodb-load-test.jar -case write -ip 127.0.0.1 -port 8529 -batchSize 50000 -threads 4
```

**Comment by mpv1989** [comment] 2017-10-27 09:36
Sure.

In the benchmark I used `collection.insert()` instead of `collection.import()` but that should not make any difference. If you can't reproduce your problem with the test maybe change the insert to import. I don't think this is the problem but when we can be sure.

**Comment by mpv1989** [comment] 2018-04-18 09:30
I will close this issue, feel free to open it again if you still need help with this topic

**Closed by mpv1989** 2018-04-18 09:30 UTC
