### ISSUE TITLE
Delete attributes not working

### ISSUE THREAD

**Issue by mxmind** [arangodb/arangodb-java-driver#239] opened 2018-11-20 01:45 UTC
Hi,
The following code not working for me (java 11)

```java
var options = new DocumentUpdateOptions().keepNull(keepNull).returnNew(true).waitForSync(true);
var entity = (DocumentUpdateEntity<VPackSlice>) operations.update(id, dto, options);
```

The `keepNull` variable is dynamically set accordingly to desired result. But unfortunately, I cannot delete the null attributes from saved record.

**Comment by mpv1989** [comment] 2018-11-20 18:33
Hi @mxmind,

there is a [test](https://github.com/arangodb/arangodb-java-driver/blob/master/src/test/java/com/arangodb/ArangoCollectionTest.java#L519) for the `keepNull` option which runs without any errors. At first glance I can't see any difference in your code.

**Comment by rashtao** [comment] 2019-09-16 08:33
Closing this issue since the feature is tested and working properly. 
@mxmind feel free to reopen this issue providing information for reproducing the problem, if any.

**Closed by rashtao** 2019-09-16 08:33 UTC
