### ISSUE TITLE
Traversal parses big numbers wrong

### ISSUE THREAD

**Issue by VadimAf** [arangodb/arangodb-java-driver#219] opened 2018-08-10 09:15 UTC
Hi!
I found the bug when Traversal and Get document from collection returns different parameter value of the same document.
The example is simple:
```
BaseDocument device = new BaseDocument();
device.addAttribute("num", Long.MAX_VALUE); /* It's a 9223372036854775807 */
String deviceKey = DB.get().collection("devices").insertDocument(device).getKey();

// #1 Option (returns 9223372036854775807, it's a right answer)
System.out.println(DB.get().collection("devices").getDocument(deviceKey, BaseDocument.class).getAttribute("num"));

// #2 Option (returns -9223372036854775616, it's a wrong answer)
TraversalOptions traversalOptions = new TraversalOptions().graphName("object-versions-graph").startVertex("devices/" + deviceKey)
                .direction(TraversalOptions.Direction.any).minDepth(0).maxDepth(0);
TraversalEntity<BaseDocument, BaseEdgeDocument> traversal = DB.get().executeTraversal(BaseDocument.class, BaseEdgeDocument.class, traversalOptions);
System.out.println(traversal.getVertices().iterator().next().getAttribute("num"));
```
I didn't find exactly from which number the problem is appears. For example, I also faces the problem with Long.MAX_VALUE - 100000000 as num. But If I set Integer.MAX_VALUE + 10 the result is expected

**Comment by mpv1989** [comment] 2018-08-10 11:25
Hi @VadimAf,

the problem is that the traversal REST API (which is used from `ArangoDatabase#executeTraversal`) uses JavaScript on the server side and JS only has floating point numbers which has a max value of `9007199254740991`.

Independent that the traversal REST API is not usable for your use case, it is also deprecated and you should switch to [AQL Graph Traversals](https://docs.arangodb.com/3.3/AQL/Graphs/Traversals.html) anyway. Here you can also work with that large numbers you have.

kind regards
Mark

**Comment by VadimAf** [comment] 2018-08-10 12:04
Mark, thanks a lot for quick response! I understood your explanation. It's true that I can use AQL instead.

Anyway, it seems confusing that the same document obtained via different arango interfaces has different param value. Surely, it's not a problem of java driver, it's more common concern

**Comment by rashtao** [comment] 2022-01-18 11:55
Closing since outdated, please reopen if still relevant.

**Closed by rashtao** 2022-01-18 11:55 UTC
