### ISSUE TITLE
Is there an officially maintained aql query builder?

### ISSUE THREAD

**Issue by AioRos85** [arangodb/arangodb-java-driver#404] opened 2021-08-25 06:57 UTC
many times you need to build some complex aql query , can you provide a way to build AQL like Java QueryDSL, or .Net dapper

**Comment by rashtao** [comment] 2021-08-25 07:33
Unfortunately at the moment there is no query builder. 
Closing as duplicate of: https://github.com/arangodb/arangodb-java-driver/issues/16
Please continue the discussion there.

**Closed by rashtao** 2021-08-25 07:33 UTC
Labels: enhancement
